server:
  port: 8088
keycloak:
  :realm: master
  :resource: clientTest
  :auth-server-url: http://10.5.4.242:8080/auth/
  :ssl-required: external
  :public-client: true
  :principal-attribute: preferred_username