/*
 * Copyright (c) 2020.
 */
package com.spring.project.demo.other.form;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.TimerTask;

/**
 * //TODO 添加说明
 *
 * @author 汪强
 * 创建时间 2020-07-22 15:53
 */
public class WinForm2 {

    private JPanel panel1;
    private JButton 启动Button;
    private JTextArea textArea1;

    public WinForm2() {
        启动Button.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {


                java.util.Timer timer = new java.util.Timer();
                timer.schedule(new TimerTask() {
                    @Override
                    public void run() {
                        textArea1.append("2020-07-16 10:11:46.087 [main] \u001B[34m[INFO]\u001B[0;39m c.spring.project.web.api.Application 50 Starting Application on wq-PC with PID 7596 (D:\\github\\code\\java\\spring-project-web1.0\\project-web-api\\target\\classes started by wq in D:\\github\\code\\java\\spring-project-web1.0\\project-web)\n");
                    }
                }, 500, 1000);

            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("生命线声光报警系统");
        frame.setContentPane(new WinForm2().panel1);
        frame.setPreferredSize(new Dimension(800, 600));

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Label1");
        panel2.add(label1);
        final JLabel label2 = new JLabel();
        label2.setText("Label2");
        panel2.add(label2);
        启动Button = new JButton();
        启动Button.setHorizontalAlignment(0);
        启动Button.setText("启动");
        启动Button.setVerifyInputWhenFocusTarget(true);
        panel2.add(启动Button);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.CENTER);
        textArea1 = new JTextArea();
        textArea1.setBackground(new Color(-16777216));
        textArea1.setForeground(new Color(-1));
        panel3.add(textArea1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
