/*
 * Copyright (c) 2020.
 */
package com.spring.project.demo.other.form;

import javax.swing.*;
import java.awt.*;

/**
 * //TODO 添加说明
 *
 * @author 汪强
 * 创建时间 2020-07-22 15:19
 */
public class WinForm extends JFrame {
    private JButton button1;
    private JPanel panel1;

    public WinForm() {
        panel1.setLayout(null);

        this.setContentPane(this.panel1);
        this.setLocationRelativeTo(null);
        //设置窗口置顶显示
        this.setAlwaysOnTop(true);
        //设置窗口显示
        this.setVisible(true);

        //对窗口设置标题
        this.setTitle("我的第一个Java窗口应用");
        //设置窗口的大小
        this.setSize(900, 500);
        //设置窗口界面的关闭按钮真的生效(也可以直接传一个3进去，JFrame.EXIT_ON_CLOSE==3，效果一样)
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        button1 = new JButton();
        button1.setText("Button");
        panel1.add(button1, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("");
        panel1.add(label1, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
