server:
  port: 8087
  #session有效期 分钟
  session-timeout: 30
spring:
  datasource:
    name: master_datasource
    url: jdbc:mysql://localhost:3306/jx_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    # java -cp druid-1.1.3.jar com.alibaba.druid.filter.config.ConfigTools 123456
#    password: XO5URsxFUTh1m/ACxsC/v3NWJ6zuuET+zZ5y1eQJxjZQJXiKcccv55YKNkA5Zu3XRj3agGGMdvbcwXPlqhjehA==
    # druid数据源
    druid:
        maxActive: 100
        initialSize: 1
        minIdle: 5
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 200
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;config.decrypt=true;config.decrypt.key=${publickKey}
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
        stat-view-servlet:
            enabled: true
        #启动configfilter
        filter:
          config:
            enabled: true
  mvc:
    #不用handler捕获异常，让springboot处理
    throw-exception-if-no-handler-found: true
#    static-path-pattern: /**
  resources:
    #静态资源是要不能访问的
    add-mappings: false
#    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
#    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html

spring.mvc.date-format: yyyy-MM-dd HH:mm:ss
# mybatis配置
mybatis:
  typeAliasesPackage: com.spring.project.web.core
  mapperLocations: classpath*:mapper/**/*.xml

swagger:
  show: true

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

publickKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJu0hBppL0OGchPs8t5p60pDDFpnuOMBU1XbPvdhkIwBj2iC0xJUlK3+BMPk4kwXS7QLkslfhK39gz1H7Hr6owsCAwEAAQ==
#禁用密码验证
#management.security.enabled: false
#security.basic.enabled: false
#security.user.name: admin
#security.user.password: admin@123
##security.basic.path=/admin
##指定管理端口和IP
#endpoints.enabled: false
#endpoints.shutdown.sensitive: false
#endpoints.shutdown.enabled: true
###endpoints.shutdown.path: /custompath
###management.context-path: /manage
#management.address: 127.0.0.1
#management.port: ${server.port}
#shutdown.whitelist: 0:0:0:0:0:0:0:1,127.0.0.1,192.168.

#启用shutdown
management:
  endpoints:
    web:
      exposure:
        include: shutdown
    #注意下面这个位置！！
  endpoint:
    shutdown:
      enabled: true

#是否开启swagger
swagger.show: true

#异常信息是否抛出 开发测试环境抛出 生产环境不抛
controller.log.err: true

#filter白名单
filter:
  xss:
    paths:
      - /*
    ignores:
      - /favicon.ico
      - /actuator/*
      - /api/**
      - /ap*
      - /static/*