server:
  port: 8080
  #session有效期 分钟
  session-timeout: 30
spring:
  datasource:
    name: master_datasource
    url: jdbc:mysql://10.5.4.58:3306/cityll-tongling?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: tongling
    #password: 123456
    # java -cp druid-1.1.3.jar com.alibaba.druid.filter.config.ConfigTools 123456
    password: XO5URsxFUTh1m/ACxsC/v3NWJ6zuuET+zZ5y1eQJxjZQJXiKcccv55YKNkA5Zu3XRj3agGGMdvbcwXPlqhjehA==
    # druid数据源
    druid:
        maxActive: 100
        initialSize: 1
        minIdle: 5
        maxWait: 10000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1 from dual
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 200
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000;config.decrypt=true;config.decrypt.key=${publickKey}
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
        stat-view-servlet:
            enabled: true
        #启动configfilter
        filter:
          config:
            enabled: true
  mvc:
    #不用handler捕获异常，让springboot处理
    throw-exception-if-no-handler-found: false
#    static-path-pattern: /**
  resources:
    #静态资源是要不能访问的
    add-mappings: false
#    static-locations: classpath:/templates/,classpath:/static/
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
#    content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html

# mybatis配置
mybatis:
  typeAliasesPackage: com.gscitylifeline.proj.tongling.web.core.dao
  mapperLocations: classpath:mapper/**/*.xml

publickKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJu0hBppL0OGchPs8t5p60pDDFpnuOMBU1XbPvdhkIwBj2iC0xJUlK3+BMPk4kwXS7QLkslfhK39gz1H7Hr6owsCAwEAAQ==

#是否开启swagger
swagger.show: true

