version: '2'
services:
  redis:
    restart: always
    image: "redis:3.2.11"
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf:ro
      - ./redis/sysctl.conf:/etc/sysctl.conf