spring:
  profiles:
    active: dev #@profiles.active@


#打包命令
#clean install -Dmaven.test.skip -Dprofiles.active=test

#@profiles.active@
# run 加参数  --spring.profiles.active=dev
# java -jar xx.jar --spring.profiles.active=dev
# mvn -P dev
# 打包 clean install -Dmaven.test.skip -Dprofiles.active=dev

